# https://github.com/houmain/spright

pack binpack


glob "white_walk_back/*.png"
glob "white_walk_front/*.png"
glob "white_walk_left/*.png"
glob "white_walk_right/*.png"

glob "white_idle_back/*.png"
glob "white_idle_front/*.png"
glob "white_idle_left/*.png"
glob "white_idle_right/*.png"


glob "black_walk_back/*.png"
glob "black_walk_front/*.png"
glob "black_walk_left/*.png"
glob "black_walk_right/*.png"

glob "black_idle_back/*.png"
glob "black_idle_front/*.png"
glob "black_idle_left/*.png"
glob "black_idle_right/*.png"


glob "orange_walk_back/*.png"
glob "orange_walk_front/*.png"
glob "orange_walk_left/*.png"
glob "orange_walk_right/*.png"

glob "orange_idle_back/*.png"
glob "orange_idle_front/*.png"
glob "orange_idle_left/*.png"
glob "orange_idle_right/*.png"


glob "green_walk_back/*.png"
glob "green_walk_front/*.png"
glob "green_walk_left/*.png"
glob "green_walk_right/*.png"

glob "green_idle_back/*.png"
glob "green_idle_front/*.png"
glob "green_idle_left/*.png"
glob "green_idle_right/*.png"


output "spritesheet.png"
description "spritesheet.json"