# https://github.com/houmain/spright

pack binpack


glob "images/white_walk_back/*.png"
glob "images/white_walk_front/*.png"
glob "images/white_walk_left/*.png"
glob "images/white_walk_right/*.png"

glob "images/white_idle_back/*.png"
glob "images/white_idle_front/*.png"
glob "images/white_idle_left/*.png"
glob "images/white_idle_right/*.png"


glob "images/black_walk_back/*.png"
glob "images/black_walk_front/*.png"
glob "images/black_walk_left/*.png"
glob "images/black_walk_right/*.png"

glob "images/black_idle_back/*.png"
glob "images/black_idle_front/*.png"
glob "images/black_idle_left/*.png"
glob "images/black_idle_right/*.png"


glob "images/orange_walk_back/*.png"
glob "images/orange_walk_front/*.png"
glob "images/orange_walk_left/*.png"
glob "images/orange_walk_right/*.png"

glob "images/orange_idle_back/*.png"
glob "images/orange_idle_front/*.png"
glob "images/orange_idle_left/*.png"
glob "images/orange_idle_right/*.png"


glob "images/green_walk_back/*.png"
glob "images/green_walk_front/*.png"
glob "images/green_walk_left/*.png"
glob "images/green_walk_right/*.png"

glob "images/green_idle_back/*.png"
glob "images/green_idle_front/*.png"
glob "images/green_idle_left/*.png"
glob "images/green_idle_right/*.png"


output "spritesheet.png"
description "spritesheet.json"